%run_training = xlsread('weizmann_training.xlsx','RUN');
%walk_training = xlsread('weizmann_training.xlsx','WALK');
%wave2_training = xlsread('weizmann_training.xlsx','WAVE2');
walk_rina_training = xlsread('weizmann_training.xlsx','WALK_RINA');
run_rina_training = xlsread('weizmann_training.xlsx','RUN_RINA');
%run_mean = mean(run_training,1);
%walk_mean = mean(walk_training,1);
%wave2_mean = mean(wave2_training,1);
walk_rina_mean = mean(walk_rina_training,1);
run_rina_mean = mean(run_rina_training,1);
mean_training = [walk_rina_mean;run_rina_mean];
xlswrite('weizmann_training_mean.xlsx',mean_training,'MEAN_RINA');